package modulo.academico;

/**
* academico/HorarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 30 de Novembro de 2014 22h44min29s BRST
*/

public final class HorarioHolder implements org.omg.CORBA.portable.Streamable
{
  public modulo.academico.Horario value = null;

  public HorarioHolder ()
  {
  }

  public HorarioHolder (modulo.academico.Horario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = modulo.academico.HorarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    modulo.academico.HorarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return modulo.academico.HorarioHelper.type ();
  }

}
