package modulo.academico;

/**
* academico/MatriculaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 30 de Novembro de 2014 22h44min29s BRST
*/

public final class MatriculaHolder implements org.omg.CORBA.portable.Streamable
{
  public modulo.academico.Matricula value = null;

  public MatriculaHolder ()
  {
  }

  public MatriculaHolder (modulo.academico.Matricula initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = modulo.academico.MatriculaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    modulo.academico.MatriculaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return modulo.academico.MatriculaHelper.type ();
  }

}
