package modulo.academico;


/**
* academico/provasHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 30 de Novembro de 2014 22h44min29s BRST
*/

abstract public class provasHelper
{
  private static String  _id = "IDL:academico/provas:1.0";

  public static void insert (org.omg.CORBA.Any a, modulo.academico.Prova[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static modulo.academico.Prova[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = modulo.academico.ProvaHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (modulo.academico.provasHelper.id (), "provas", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static modulo.academico.Prova[] read (org.omg.CORBA.portable.InputStream istream)
  {
    modulo.academico.Prova value[] = null;
    int _len0 = istream.read_long ();
    value = new modulo.academico.Prova[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = modulo.academico.ProvaHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, modulo.academico.Prova[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      modulo.academico.ProvaHelper.write (ostream, value[_i0]);
  }

}
