
package pacote.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CentralAlunoService", targetNamespace = "http://webservice_guniver/", wsdlLocation = "http://localhost:8080/criarCompromisso?wsdl")
public class CentralAlunoService
    extends Service
{

    private final static URL CENTRALALUNOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CENTRALALUNOSERVICE_EXCEPTION;
    private final static QName CENTRALALUNOSERVICE_QNAME = new QName("http://webservice_guniver/", "CentralAlunoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/criarCompromisso?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTRALALUNOSERVICE_WSDL_LOCATION = url;
        CENTRALALUNOSERVICE_EXCEPTION = e;
    }

    public CentralAlunoService() {
        super(__getWsdlLocation(), CENTRALALUNOSERVICE_QNAME);
    }

    public CentralAlunoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTRALALUNOSERVICE_QNAME, features);
    }

    public CentralAlunoService(URL wsdlLocation) {
        super(wsdlLocation, CENTRALALUNOSERVICE_QNAME);
    }

    public CentralAlunoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTRALALUNOSERVICE_QNAME, features);
    }

    public CentralAlunoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CentralAlunoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CentralAluno
     */
    @WebEndpoint(name = "CentralAlunoPort")
    public CentralAluno getCentralAlunoPort() {
        return super.getPort(new QName("http://webservice_guniver/", "CentralAlunoPort"), CentralAluno.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CentralAluno
     */
    @WebEndpoint(name = "CentralAlunoPort")
    public CentralAluno getCentralAlunoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice_guniver/", "CentralAlunoPort"), CentralAluno.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTRALALUNOSERVICE_EXCEPTION!= null) {
            throw CENTRALALUNOSERVICE_EXCEPTION;
        }
        return CENTRALALUNOSERVICE_WSDL_LOCATION;
    }

}
