module academico {

	struct Aluno {
		long codigo;
		string nome;
	};

	struct Disciplina{
		long codigo;
		string nome;
	};

	struct Turma {
		long codigo;
		string nome;
		short ano;
		short semestre;
		Disciplina disciplina;
	};

	struct Matricula {
		Aluno aluno;
		Turma turma;
	};

	struct Prova {
		string descricao;
		Aluno aluno;
		Turma turma;
		float nota;
	};

	struct Horario {
		string horario;
		string sala;
	};


	typedef sequence<Horario> horarios;
	typedef sequence<Prova> provas;
	//typedef sequence<notasAlunos> notasTurmas;
	typedef sequence<Matricula> matriculas;
	//typedef sequence<Disciplina> disciplinas;

	//enum SituacaoMatricula { pago, atrazado, a_pagar };

  interface IAcademico {
	  provas getNotasAluno(in Aluno aluno, in Turma turma);
	  Matricula getMatricula(in Aluno aluno, in Disciplina disciplina);
	  matriculas getMatriculas(in Aluno aluno);
	  matriculas getMatriculasSemestre(in Aluno aluno, in short ano, in short semestre);
	  boolean matricular(in Aluno aluno, in Turma turma, out string mensagemErro);
	  horarios getHorarios();
	  //boolean cadastrarTurma(in Turma turma, out string mensagemErro);
	  //boolean cadastrarDisciplina(in Disciplina disciplina, out string mensagemErro);
	  boolean cadastrarProva(in Prova prova, out string mensagemErro);
	  //boolean getDisciplina(in long codigo, out Disciplina disciplina);
	  //disciplinas getDisciplinas();
  };
};
