package br.furb.guniver.modelo.academico;


/**
* br/furb/guniver/modelo/academico/Disciplina.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 3 de Dezembro de 2014 03h40min06s BRST
*/

public final class Disciplina implements org.omg.CORBA.portable.IDLEntity
{
  public int codigo = (int)0;
  public String nome = null;

  public Disciplina ()
  {
  } // ctor

  public Disciplina (int _codigo, String _nome)
  {
    codigo = _codigo;
    nome = _nome;
  } // ctor

} // class Disciplina
