package br.furb.guniver.modelo.academico;


/**
* br/furb/guniver/modelo/academico/horariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 3 de Dezembro de 2014 04h32min40s BRST
*/

public final class horariosHolder implements org.omg.CORBA.portable.Streamable
{
  public br.furb.guniver.modelo.academico.Horario value[] = null;

  public horariosHolder ()
  {
  }

  public horariosHolder (br.furb.guniver.modelo.academico.Horario[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.furb.guniver.modelo.academico.horariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.furb.guniver.modelo.academico.horariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.furb.guniver.modelo.academico.horariosHelper.type ();
  }

}
