package br.furb.guniver.modelo.academico;


/**
* br/furb/guniver/modelo/academico/IAcademico.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 3 de Dezembro de 2014 04h32min40s BRST
*/


//enum SituacaoMatricula { pago, atrazado, a_pagar };
public interface IAcademico extends IAcademicoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IAcademico
