package br.furb.guniver.modelo.academico;

/**
* br/furb/guniver/modelo/academico/IAcademicoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Terça-feira, 2 de Dezembro de 2014 23h28min37s BRST
*/


//enum SituacaoMatricula { pago, atrazado, a_pagar };
public final class IAcademicoHolder implements org.omg.CORBA.portable.Streamable
{
  public br.furb.guniver.modelo.academico.IAcademico value = null;

  public IAcademicoHolder ()
  {
  }

  public IAcademicoHolder (br.furb.guniver.modelo.academico.IAcademico initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.furb.guniver.modelo.academico.IAcademicoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.furb.guniver.modelo.academico.IAcademicoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.furb.guniver.modelo.academico.IAcademicoHelper.type ();
  }

}
