package br.furb.guniver.modelo.academico;


/**
* br/furb/guniver/modelo/academico/IAcademicoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 3 de Dezembro de 2014 04h32min40s BRST
*/


//enum SituacaoMatricula { pago, atrazado, a_pagar };
public interface IAcademicoOperations 
{
  br.furb.guniver.modelo.academico.Prova[] getProvasAluno (int codigoAluno, int codigoTurma);
  br.furb.guniver.modelo.academico.Prova[] getProvas ();
  br.furb.guniver.modelo.academico.Matricula[] getMatriculasAluno (int codigoAluno);
  br.furb.guniver.modelo.academico.Matricula[] getMatriculasTurma (int codigoTurma);

  //matriculas getMatriculasSemestre(in long codigoAluno, in short ano, in short semestre);
  boolean cadastrarMatricula (int codigoAluno, int codigoTurma, org.omg.CORBA.StringHolder mensagemErro);
  br.furb.guniver.modelo.academico.Horario[] getHorarios (int codigoTurma);

  //boolean cadastrarDisciplina(in Disciplina disciplina, out string mensagemErro);
  boolean cadastrarProva (br.furb.guniver.modelo.academico.Prova prova, org.omg.CORBA.StringHolder mensagemErro);
} // interface IAcademicoOperations
