package br.furb.guniver.modelo.academico;


/**
* br/furb/guniver/modelo/academico/matriculasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Segunda-feira, 1 de Dezembro de 2014 23h11min42s BRST
*/


//typedef sequence<notasAlunos> notasTurmas;
public final class matriculasHolder implements org.omg.CORBA.portable.Streamable
{
  public br.furb.guniver.modelo.academico.Matricula value[] = null;

  public matriculasHolder ()
  {
  }

  public matriculasHolder (br.furb.guniver.modelo.academico.Matricula[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.furb.guniver.modelo.academico.matriculasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.furb.guniver.modelo.academico.matriculasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.furb.guniver.modelo.academico.matriculasHelper.type ();
  }

}
