package br.furb.guniver.modelo.academico;


/**
* br/furb/guniver/modelo/academico/Matricula.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 3 de Dezembro de 2014 04h32min40s BRST
*/

public final class Matricula implements org.omg.CORBA.portable.IDLEntity
{
  public int codigoAluno = (int)0;
  public int codigoTurma = (int)0;

  public Matricula ()
  {
  } // ctor

  public Matricula (int _codigoAluno, int _codigoTurma)
  {
    codigoAluno = _codigoAluno;
    codigoTurma = _codigoTurma;
  } // ctor

} // class Matricula
