package br.furb.guniver.modelo.academico;


/**
* br/furb/guniver/modelo/academico/Matricula.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 3 de Dezembro de 2014 03h40min06s BRST
*/

public final class Matricula implements org.omg.CORBA.portable.IDLEntity
{
  public br.furb.guniver.modelo.academico.Aluno aluno = null;
  public br.furb.guniver.modelo.academico.Turma turma = null;

  public Matricula ()
  {
  } // ctor

  public Matricula (br.furb.guniver.modelo.academico.Aluno _aluno, br.furb.guniver.modelo.academico.Turma _turma)
  {
    aluno = _aluno;
    turma = _turma;
  } // ctor

} // class Matricula
