package br.furb.guniver.modelo.academico;


/**
* br/furb/guniver/modelo/academico/Prova.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Segunda-feira, 1 de Dezembro de 2014 23h11min42s BRST
*/

public final class Prova implements org.omg.CORBA.portable.IDLEntity
{
  public String descricao = null;
  public br.furb.guniver.modelo.academico.Aluno aluno = null;
  public br.furb.guniver.modelo.academico.Turma turma = null;
  public float nota = (float)0;

  public Prova ()
  {
  } // ctor

  public Prova (String _descricao, br.furb.guniver.modelo.academico.Aluno _aluno, br.furb.guniver.modelo.academico.Turma _turma, float _nota)
  {
    descricao = _descricao;
    aluno = _aluno;
    turma = _turma;
    nota = _nota;
  } // ctor

} // class Prova
