package br.furb.guniver.modelo.academico;


/**
* br/furb/guniver/modelo/academico/Prova.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 3 de Dezembro de 2014 04h32min40s BRST
*/

public final class Prova implements org.omg.CORBA.portable.IDLEntity
{
  public String descricao = null;
  public int codigoAluno = (int)0;
  public int codigoTurma = (int)0;
  public float nota = (float)0;

  public Prova ()
  {
  } // ctor

  public Prova (String _descricao, int _codigoAluno, int _codigoTurma, float _nota)
  {
    descricao = _descricao;
    codigoAluno = _codigoAluno;
    codigoTurma = _codigoTurma;
    nota = _nota;
  } // ctor

} // class Prova
