package academico;

/**
* academico/HorarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Sexta-feira, 28 de Novembro de 2014 01h17min25s BRST
*/

public final class HorarioHolder implements org.omg.CORBA.portable.Streamable
{
  public academico.Horario value = null;

  public HorarioHolder ()
  {
  }

  public HorarioHolder (academico.Horario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = academico.HorarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    academico.HorarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return academico.HorarioHelper.type ();
  }

}
