package academico;


/**
* academico/IAcademicoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Sexta-feira, 28 de Novembro de 2014 01h17min25s BRST
*/


//enum SituacaoMatricula { pago, atrazado, a_pagar };
public interface IAcademicoOperations 
{
  academico.Prova[] getNotasAluno (academico.Aluno aluno, academico.Turma turma);
  academico.Matricula getMatricula (academico.Aluno aluno, academico.Disciplina disciplina);
  academico.Matricula[] getMatriculasAluno (academico.Aluno aluno);
  academico.Matricula[] getMatriculasTurma (academico.Turma turma);
  academico.Matricula[] getMatriculasSemestre (academico.Aluno aluno, short ano, short semestre);
  boolean matricular (academico.Aluno aluno, academico.Turma turma, org.omg.CORBA.StringHolder mensagemErro);
  academico.Horario[] getHorarios ();

  //boolean cadastrarDisciplina(in Disciplina disciplina, out string mensagemErro);
  boolean cadastrarProva (academico.Prova prova, org.omg.CORBA.StringHolder mensagemErro);
} // interface IAcademicoOperations
