package academico;


/**
* academico/_IAcademicoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 16 de Novembro de 2014 22h50min10s BRST
*/

public class _IAcademicoStub extends org.omg.CORBA.portable.ObjectImpl implements academico.IAcademico
{

  public float[] getNotasAlunoTurma (academico.Aluno aluno, academico.Turma turma)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNotasAlunoTurma", true);
                academico.AlunoHelper.write ($out, aluno);
                academico.TurmaHelper.write ($out, turma);
                $in = _invoke ($out);
                float $result[] = academico.notasAlunosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNotasAlunoTurma (aluno, turma        );
            } finally {
                _releaseReply ($in);
            }
  } // getNotasAlunoTurma

  public float[][] getNotasTurma (academico.Turma turma)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNotasTurma", true);
                academico.TurmaHelper.write ($out, turma);
                $in = _invoke ($out);
                float $result[][] = academico.notasTurmasHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNotasTurma (turma        );
            } finally {
                _releaseReply ($in);
            }
  } // getNotasTurma

  public academico.Ocorrencia[] getOcorrencias (academico.Aluno aluno)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getOcorrencias", true);
                academico.AlunoHelper.write ($out, aluno);
                $in = _invoke ($out);
                academico.Ocorrencia $result[] = academico.ocorrenciasHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getOcorrencias (aluno        );
            } finally {
                _releaseReply ($in);
            }
  } // getOcorrencias

  public academico.Matricula getMatricula (academico.Aluno aluno, academico.Disciplina disciplina)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMatricula", true);
                academico.AlunoHelper.write ($out, aluno);
                academico.DisciplinaHelper.write ($out, disciplina);
                $in = _invoke ($out);
                academico.Matricula $result = academico.MatriculaHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMatricula (aluno, disciplina        );
            } finally {
                _releaseReply ($in);
            }
  } // getMatricula

  public academico.Matricula[] getMatriculas (academico.Aluno aluno)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMatriculas", true);
                academico.AlunoHelper.write ($out, aluno);
                $in = _invoke ($out);
                academico.Matricula $result[] = academico.matriculasHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMatriculas (aluno        );
            } finally {
                _releaseReply ($in);
            }
  } // getMatriculas

  public academico.SituacaoMatricula matricular (academico.Aluno aluno)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("matricular", true);
                academico.AlunoHelper.write ($out, aluno);
                $in = _invoke ($out);
                academico.SituacaoMatricula $result = academico.SituacaoMatriculaHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return matricular (aluno        );
            } finally {
                _releaseReply ($in);
            }
  } // matricular

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:academico/IAcademico:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IAcademicoStub
