package academico;

/**
* academico/CursoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 19 de Novembro de 2014 00h27min51s BRST
*/

public final class CursoHolder implements org.omg.CORBA.portable.Streamable
{
  public academico.Curso value = null;

  public CursoHolder ()
  {
  }

  public CursoHolder (academico.Curso initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = academico.CursoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    academico.CursoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return academico.CursoHelper.type ();
  }

}
