package academico;


/**
* academico/Horario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 26 de Novembro de 2014 21h55min02s BRST
*/

public final class Horario implements org.omg.CORBA.portable.IDLEntity
{
  public String horario = null;
  public String sala = null;

  public Horario ()
  {
  } // ctor

  public Horario (String _horario, String _sala)
  {
    horario = _horario;
    sala = _sala;
  } // ctor

} // class Horario
