package academico;


/**
* academico/IAcademicoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 16 de Novembro de 2014 22h50min10s BRST
*/

public abstract class IAcademicoPOA extends org.omg.PortableServer.Servant
 implements academico.IAcademicoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getNotasAlunoTurma", new java.lang.Integer (0));
    _methods.put ("getNotasTurma", new java.lang.Integer (1));
    _methods.put ("getOcorrencias", new java.lang.Integer (2));
    _methods.put ("getMatricula", new java.lang.Integer (3));
    _methods.put ("getMatriculas", new java.lang.Integer (4));
    _methods.put ("matricular", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // academico/IAcademico/getNotasAlunoTurma
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         academico.Turma turma = academico.TurmaHelper.read (in);
         float $result[] = null;
         $result = this.getNotasAlunoTurma (aluno, turma);
         out = $rh.createReply();
         academico.notasAlunosHelper.write (out, $result);
         break;
       }

       case 1:  // academico/IAcademico/getNotasTurma
       {
         academico.Turma turma = academico.TurmaHelper.read (in);
         float $result[][] = null;
         $result = this.getNotasTurma (turma);
         out = $rh.createReply();
         academico.notasTurmasHelper.write (out, $result);
         break;
       }

       case 2:  // academico/IAcademico/getOcorrencias
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         academico.Ocorrencia $result[] = null;
         $result = this.getOcorrencias (aluno);
         out = $rh.createReply();
         academico.ocorrenciasHelper.write (out, $result);
         break;
       }

       case 3:  // academico/IAcademico/getMatricula
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         academico.Disciplina disciplina = academico.DisciplinaHelper.read (in);
         academico.Matricula $result = null;
         $result = this.getMatricula (aluno, disciplina);
         out = $rh.createReply();
         academico.MatriculaHelper.write (out, $result);
         break;
       }

       case 4:  // academico/IAcademico/getMatriculas
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         academico.Matricula $result[] = null;
         $result = this.getMatriculas (aluno);
         out = $rh.createReply();
         academico.matriculasHelper.write (out, $result);
         break;
       }

       case 5:  // academico/IAcademico/matricular
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         academico.SituacaoMatricula $result = null;
         $result = this.matricular (aluno);
         out = $rh.createReply();
         academico.SituacaoMatriculaHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:academico/IAcademico:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IAcademico _this() 
  {
    return IAcademicoHelper.narrow(
    super._this_object());
  }

  public IAcademico _this(org.omg.CORBA.ORB orb) 
  {
    return IAcademicoHelper.narrow(
    super._this_object(orb));
  }


} // class IAcademicoPOA
