package academico;


/**
* academico/IAcademico.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quinta-feira, 27 de Novembro de 2014 01h06min29s BRST
*/


//enum SituacaoMatricula { pago, atrazado, a_pagar };
public interface IAcademico extends IAcademicoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IAcademico
