package academico;


/**
* academico/IAcademicoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 19 de Novembro de 2014 01h23min34s BRST
*/

public interface IAcademicoOperations 
{
  float[] getNotasAluno (academico.Aluno aluno, academico.Turma turma);
  academico.Ocorrencia[] getOcorrencias (academico.Aluno aluno);
  academico.Matricula getMatricula (academico.Aluno aluno, academico.Disciplina disciplina);
  academico.Matricula[] getMatriculas (academico.Aluno aluno);
  boolean matricular (academico.Aluno aluno, academico.Turma turma, org.omg.CORBA.StringHolder mensagemErro);
  boolean cadastrarTurma (academico.Turma turma, org.omg.CORBA.StringHolder mensagemErro);
  boolean cadastrarDisciplina (academico.Disciplina disciplina, org.omg.CORBA.StringHolder mensagemErro);
  boolean cadastrarProva (academico.Prova prova, org.omg.CORBA.StringHolder mensagemErro);
  boolean getDisciplina (int codigo, academico.DisciplinaHolder disciplina);
  academico.Disciplina[] getDisciplinas ();
} // interface IAcademicoOperations
