package academico;


/**
* academico/Matricula.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 16 de Novembro de 2014 22h50min10s BRST
*/

public final class Matricula implements org.omg.CORBA.portable.IDLEntity
{
  public int codigo = (int)0;
  public academico.Aluno aluno = null;
  public academico.Disciplina disciplina = null;

  public Matricula ()
  {
  } // ctor

  public Matricula (int _codigo, academico.Aluno _aluno, academico.Disciplina _disciplina)
  {
    codigo = _codigo;
    aluno = _aluno;
    disciplina = _disciplina;
  } // ctor

} // class Matricula
