package academico;


/**
* academico/provasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 26 de Novembro de 2014 23h22min21s BRST
*/

public final class provasHolder implements org.omg.CORBA.portable.Streamable
{
  public academico.Prova value[] = null;

  public provasHolder ()
  {
  }

  public provasHolder (academico.Prova[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = academico.provasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    academico.provasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return academico.provasHelper.type ();
  }

}
