package academico;


/**
* academico/SituacaoMatricula.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 16 de Novembro de 2014 22h50min10s BRST
*/

public class SituacaoMatricula implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static academico.SituacaoMatricula[] __array = new academico.SituacaoMatricula [__size];

  public static final int _pago = 0;
  public static final academico.SituacaoMatricula pago = new academico.SituacaoMatricula(_pago);
  public static final int _atrazado = 1;
  public static final academico.SituacaoMatricula atrazado = new academico.SituacaoMatricula(_atrazado);
  public static final int _apagar = 2;
  public static final academico.SituacaoMatricula apagar = new academico.SituacaoMatricula(_apagar);

  public int value ()
  {
    return __value;
  }

  public static academico.SituacaoMatricula from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SituacaoMatricula (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class SituacaoMatricula
