package servico.academico;

/**
* academico/AlunoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 30 de Novembro de 2014 22h44min29s BRST
*/

public final class AlunoHolder implements org.omg.CORBA.portable.Streamable
{
  public servico.academico.Aluno value = null;

  public AlunoHolder ()
  {
  }

  public AlunoHolder (servico.academico.Aluno initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servico.academico.AlunoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servico.academico.AlunoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servico.academico.AlunoHelper.type ();
  }

}
