package servico.academico;

/**
* academico/DisciplinaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 30 de Novembro de 2014 22h44min29s BRST
*/

public final class DisciplinaHolder implements org.omg.CORBA.portable.Streamable
{
  public servico.academico.Disciplina value = null;

  public DisciplinaHolder ()
  {
  }

  public DisciplinaHolder (servico.academico.Disciplina initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servico.academico.DisciplinaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servico.academico.DisciplinaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servico.academico.DisciplinaHelper.type ();
  }

}
