package servico.academico;

/**
* academico/IAcademicoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 30 de Novembro de 2014 22h44min29s BRST
*/


//enum SituacaoMatricula { pago, atrazado, a_pagar };
public final class IAcademicoHolder implements org.omg.CORBA.portable.Streamable
{
  public servico.academico.IAcademico value = null;

  public IAcademicoHolder ()
  {
  }

  public IAcademicoHolder (servico.academico.IAcademico initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servico.academico.IAcademicoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servico.academico.IAcademicoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servico.academico.IAcademicoHelper.type ();
  }

}
