package servico.academico;

/**
* academico/SituacaoMatriculaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 19 de Novembro de 2014 22h28min20s BRST
*/

public final class SituacaoMatriculaHolder implements org.omg.CORBA.portable.Streamable
{
  public servico.academico.SituacaoMatricula value = null;

  public SituacaoMatriculaHolder ()
  {
  }

  public SituacaoMatriculaHolder (servico.academico.SituacaoMatricula initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servico.academico.SituacaoMatriculaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servico.academico.SituacaoMatriculaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servico.academico.SituacaoMatriculaHelper.type ();
  }

}
