package servico.academico;

/**
* academico/TurmaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 30 de Novembro de 2014 22h44min29s BRST
*/

public final class TurmaHolder implements org.omg.CORBA.portable.Streamable
{
  public servico.academico.Turma value = null;

  public TurmaHolder ()
  {
  }

  public TurmaHolder (servico.academico.Turma initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servico.academico.TurmaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servico.academico.TurmaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servico.academico.TurmaHelper.type ();
  }

}
