package academico;


/**
* academico/IAcademicoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 16 de Novembro de 2014 22h44min53s BRST
*/

public interface IAcademicoOperations 
{
  float[] getNotasAlunoTurma (academico.Aluno aluno, academico.Turma turma);
  float[][] getNotasTurma (academico.Turma turma);
  academico.Ocorrencia[] getOcorrencias (academico.Aluno aluno);
  academico.Matricula getMatricula (academico.Aluno aluno, academico.Disciplina disciplina);
  academico.Matricula[] getMatriculas (academico.Aluno aluno);
  academico.SituacaoMatricula matricular (academico.Aluno aluno);
} // interface IAcademicoOperations
