package academico;


/**
* academico/IAcademicoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 26 de Novembro de 2014 00h01min29s BRST
*/


//enum SituacaoMatricula { pago, atrazado, a_pagar };
public interface IAcademicoOperations 
{
  float[] getNotasAluno (academico.Aluno aluno, academico.Turma turma);
  academico.Matricula getMatricula (academico.Aluno aluno, academico.Disciplina disciplina);
  academico.Matricula[] getMatriculas (academico.Aluno aluno);
  academico.Matricula[] getMatriculasSemestre (academico.Aluno aluno, short ano, short semestre);
  boolean matricular (academico.Aluno aluno, academico.Turma turma, org.omg.CORBA.StringHolder mensagemErro);
  academico.Horario[] getHorarios ();
} // interface IAcademicoOperations
