package academico;


/**
* academico/IAcademicoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 19 de Novembro de 2014 22h14min40s BRST
*/

public abstract class IAcademicoPOA extends org.omg.PortableServer.Servant
 implements academico.IAcademicoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getNotasAluno", new java.lang.Integer (0));
    _methods.put ("getMatricula", new java.lang.Integer (1));
    _methods.put ("getMatriculas", new java.lang.Integer (2));
    _methods.put ("getMatriculasSemestre", new java.lang.Integer (3));
    _methods.put ("matricular", new java.lang.Integer (4));
    _methods.put ("cadastrarTurma", new java.lang.Integer (5));
    _methods.put ("cadastrarDisciplina", new java.lang.Integer (6));
    _methods.put ("cadastrarProva", new java.lang.Integer (7));
    _methods.put ("getDisciplina", new java.lang.Integer (8));
    _methods.put ("getDisciplinas", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // academico/IAcademico/getNotasAluno
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         academico.Turma turma = academico.TurmaHelper.read (in);
         float $result[] = null;
         $result = this.getNotasAluno (aluno, turma);
         out = $rh.createReply();
         academico.notasAlunosHelper.write (out, $result);
         break;
       }

       case 1:  // academico/IAcademico/getMatricula
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         academico.Disciplina disciplina = academico.DisciplinaHelper.read (in);
         academico.Matricula $result = null;
         $result = this.getMatricula (aluno, disciplina);
         out = $rh.createReply();
         academico.MatriculaHelper.write (out, $result);
         break;
       }

       case 2:  // academico/IAcademico/getMatriculas
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         academico.Matricula $result[] = null;
         $result = this.getMatriculas (aluno);
         out = $rh.createReply();
         academico.matriculasHelper.write (out, $result);
         break;
       }

       case 3:  // academico/IAcademico/getMatriculasSemestre
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         short ano = in.read_short ();
         short semestre = in.read_short ();
         academico.Matricula $result[] = null;
         $result = this.getMatriculasSemestre (aluno, ano, semestre);
         out = $rh.createReply();
         academico.matriculasHelper.write (out, $result);
         break;
       }

       case 4:  // academico/IAcademico/matricular
       {
         academico.Aluno aluno = academico.AlunoHelper.read (in);
         academico.Turma turma = academico.TurmaHelper.read (in);
         org.omg.CORBA.StringHolder mensagemErro = new org.omg.CORBA.StringHolder ();
         boolean $result = false;
         $result = this.matricular (aluno, turma, mensagemErro);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_string (mensagemErro.value);
         break;
       }

       case 5:  // academico/IAcademico/cadastrarTurma
       {
         academico.Turma turma = academico.TurmaHelper.read (in);
         org.omg.CORBA.StringHolder mensagemErro = new org.omg.CORBA.StringHolder ();
         boolean $result = false;
         $result = this.cadastrarTurma (turma, mensagemErro);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_string (mensagemErro.value);
         break;
       }

       case 6:  // academico/IAcademico/cadastrarDisciplina
       {
         academico.Disciplina disciplina = academico.DisciplinaHelper.read (in);
         org.omg.CORBA.StringHolder mensagemErro = new org.omg.CORBA.StringHolder ();
         boolean $result = false;
         $result = this.cadastrarDisciplina (disciplina, mensagemErro);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_string (mensagemErro.value);
         break;
       }

       case 7:  // academico/IAcademico/cadastrarProva
       {
         academico.Prova prova = academico.ProvaHelper.read (in);
         org.omg.CORBA.StringHolder mensagemErro = new org.omg.CORBA.StringHolder ();
         boolean $result = false;
         $result = this.cadastrarProva (prova, mensagemErro);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_string (mensagemErro.value);
         break;
       }

       case 8:  // academico/IAcademico/getDisciplina
       {
         int codigo = in.read_long ();
         academico.DisciplinaHolder disciplina = new academico.DisciplinaHolder ();
         boolean $result = false;
         $result = this.getDisciplina (codigo, disciplina);
         out = $rh.createReply();
         out.write_boolean ($result);
         academico.DisciplinaHelper.write (out, disciplina.value);
         break;
       }

       case 9:  // academico/IAcademico/getDisciplinas
       {
         academico.Disciplina $result[] = null;
         $result = this.getDisciplinas ();
         out = $rh.createReply();
         academico.disciplinasHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:academico/IAcademico:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IAcademico _this() 
  {
    return IAcademicoHelper.narrow(
    super._this_object());
  }

  public IAcademico _this(org.omg.CORBA.ORB orb) 
  {
    return IAcademicoHelper.narrow(
    super._this_object(orb));
  }


} // class IAcademicoPOA
