package academico;


/**
* academico/ocorrenciasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 16 de Novembro de 2014 22h44min53s BRST
*/

public final class ocorrenciasHolder implements org.omg.CORBA.portable.Streamable
{
  public academico.Ocorrencia value[] = null;

  public ocorrenciasHolder ()
  {
  }

  public ocorrenciasHolder (academico.Ocorrencia[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = academico.ocorrenciasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    academico.ocorrenciasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return academico.ocorrenciasHelper.type ();
  }

}
