package academico;


/**
* academico/Ocorrencia.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Domingo, 16 de Novembro de 2014 22h44min53s BRST
*/

public final class Ocorrencia implements org.omg.CORBA.portable.IDLEntity
{
  public String descricao = null;

  public Ocorrencia ()
  {
  } // ctor

  public Ocorrencia (String _descricao)
  {
    descricao = _descricao;
  } // ctor

} // class Ocorrencia
