package br.furb.guniver.modelo.academico;


/**
* academico/disciplinasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 19 de Novembro de 2014 22h28min20s BRST
*/

public final class disciplinasHolder implements org.omg.CORBA.portable.Streamable
{
  public br.furb.guniver.modelo.academico.Disciplina value[] = null;

  public disciplinasHolder ()
  {
  }

  public disciplinasHolder (br.furb.guniver.modelo.academico.Disciplina[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.furb.guniver.modelo.academico.disciplinasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.furb.guniver.modelo.academico.disciplinasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.furb.guniver.modelo.academico.disciplinasHelper.type ();
  }

}
