package academico.model;


/**
* academico/_IAcademicoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 26 de Novembro de 2014 00h01min29s BRST
*/


//enum SituacaoMatricula { pago, atrazado, a_pagar };
public class _IAcademicoStub extends org.omg.CORBA.portable.ObjectImpl implements academico.model.IAcademico
{

  public float[] getNotasAluno (academico.model.Aluno aluno, academico.model.Turma turma)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNotasAluno", true);
                academico.model.AlunoHelper.write ($out, aluno);
                academico.model.TurmaHelper.write ($out, turma);
                $in = _invoke ($out);
                float $result[] = academico.model.notasAlunosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNotasAluno (aluno, turma        );
            } finally {
                _releaseReply ($in);
            }
  } // getNotasAluno

  public academico.model.Matricula getMatricula (academico.model.Aluno aluno, academico.model.Disciplina disciplina)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMatricula", true);
                academico.model.AlunoHelper.write ($out, aluno);
                academico.model.DisciplinaHelper.write ($out, disciplina);
                $in = _invoke ($out);
                academico.model.Matricula $result = academico.model.MatriculaHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMatricula (aluno, disciplina        );
            } finally {
                _releaseReply ($in);
            }
  } // getMatricula

  public academico.model.Matricula[] getMatriculas (academico.model.Aluno aluno)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMatriculas", true);
                academico.model.AlunoHelper.write ($out, aluno);
                $in = _invoke ($out);
                academico.model.Matricula $result[] = academico.model.matriculasHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMatriculas (aluno        );
            } finally {
                _releaseReply ($in);
            }
  } // getMatriculas

  public academico.model.Matricula[] getMatriculasSemestre (academico.model.Aluno aluno, short ano, short semestre)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMatriculasSemestre", true);
                academico.model.AlunoHelper.write ($out, aluno);
                $out.write_short (ano);
                $out.write_short (semestre);
                $in = _invoke ($out);
                academico.model.Matricula $result[] = academico.model.matriculasHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMatriculasSemestre (aluno, ano, semestre        );
            } finally {
                _releaseReply ($in);
            }
  } // getMatriculasSemestre

  public boolean matricular (academico.model.Aluno aluno, academico.model.Turma turma, org.omg.CORBA.StringHolder mensagemErro)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("matricular", true);
                academico.model.AlunoHelper.write ($out, aluno);
                academico.model.TurmaHelper.write ($out, turma);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                mensagemErro.value = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return matricular (aluno, turma, mensagemErro        );
            } finally {
                _releaseReply ($in);
            }
  } // matricular

  public academico.model.Horario[] getHorarios ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getHorarios", true);
                $in = _invoke ($out);
                academico.model.Horario $result[] = academico.model.horariosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getHorarios (        );
            } finally {
                _releaseReply ($in);
            }
  } // getHorarios

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:academico/IAcademico:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IAcademicoStub
