package academico.model;


/**
* academico/horariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 26 de Novembro de 2014 00h01min29s BRST
*/

public final class horariosHolder implements org.omg.CORBA.portable.Streamable
{
  public academico.model.Horario value[] = null;

  public horariosHolder ()
  {
  }

  public horariosHolder (academico.model.Horario[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = academico.model.horariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    academico.model.horariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return academico.model.horariosHelper.type ();
  }

}
