package academico.model;

/**
* academico/HorarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 26 de Novembro de 2014 00h01min29s BRST
*/

public final class HorarioHolder implements org.omg.CORBA.portable.Streamable
{
  public academico.model.Horario value = null;

  public HorarioHolder ()
  {
  }

  public HorarioHolder (academico.model.Horario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = academico.model.HorarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    academico.model.HorarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return academico.model.HorarioHelper.type ();
  }

}
