package academico.model;


/**
* academico/IAcademicoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 26 de Novembro de 2014 00h01min29s BRST
*/


//enum SituacaoMatricula { pago, atrazado, a_pagar };
public interface IAcademicoOperations 
{
  float[] getNotasAluno (academico.model.Aluno aluno, academico.model.Turma turma);
  academico.model.Matricula getMatricula (academico.model.Aluno aluno, academico.model.Disciplina disciplina);
  academico.model.Matricula[] getMatriculas (academico.model.Aluno aluno);
  academico.model.Matricula[] getMatriculasSemestre (academico.model.Aluno aluno, short ano, short semestre);
  boolean matricular (academico.model.Aluno aluno, academico.model.Turma turma, org.omg.CORBA.StringHolder mensagemErro);
  academico.model.Horario[] getHorarios ();
} // interface IAcademicoOperations
