package academico.model;


/**
* academico/MatriculaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 26 de Novembro de 2014 00h01min29s BRST
*/

abstract public class MatriculaHelper
{
  private static String  _id = "IDL:academico/Matricula:1.0";

  public static void insert (org.omg.CORBA.Any a, academico.model.Matricula that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static academico.model.Matricula extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = academico.model.AlunoHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "aluno",
            _tcOf_members0,
            null);
          _tcOf_members0 = academico.model.TurmaHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "turma",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (academico.model.MatriculaHelper.id (), "Matricula", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static academico.model.Matricula read (org.omg.CORBA.portable.InputStream istream)
  {
    academico.model.Matricula value = new academico.model.Matricula ();
    value.aluno = academico.model.AlunoHelper.read (istream);
    value.turma = academico.model.TurmaHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, academico.model.Matricula value)
  {
    academico.model.AlunoHelper.write (ostream, value.aluno);
    academico.model.TurmaHelper.write (ostream, value.turma);
  }

}
