package academico.model;


/**
* academico/notasTurmasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 19 de Novembro de 2014 22h28min20s BRST
*/

public final class notasTurmasHolder implements org.omg.CORBA.portable.Streamable
{
  public float value[][] = null;

  public notasTurmasHolder ()
  {
  }

  public notasTurmasHolder (float[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = academico.model.notasTurmasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    academico.model.notasTurmasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return academico.model.notasTurmasHelper.type ();
  }

}
