package academico.model;


/**
* academico/SituacaoMatricula.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Academico.idl
* Quarta-feira, 19 de Novembro de 2014 22h28min20s BRST
*/

public class SituacaoMatricula implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static academico.model.SituacaoMatricula[] __array = new academico.model.SituacaoMatricula [__size];

  public static final int _pago = 0;
  public static final academico.model.SituacaoMatricula pago = new academico.model.SituacaoMatricula(_pago);
  public static final int _atrazado = 1;
  public static final academico.model.SituacaoMatricula atrazado = new academico.model.SituacaoMatricula(_atrazado);
  public static final int _a_pagar = 2;
  public static final academico.model.SituacaoMatricula a_pagar = new academico.model.SituacaoMatricula(_a_pagar);

  public int value ()
  {
    return __value;
  }

  public static academico.model.SituacaoMatricula from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SituacaoMatricula (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class SituacaoMatricula
